name: CI

permissions: { }

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  linuxtest:
    name: "linuxtest (${{ matrix.platform.target }})"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          rustup target add powerpc64le-unknown-linux-gnu
          uv pip install \
            maturin \
            'ziglang==0.14.0' \
            cffi \
            patchelf \
            --system
          maturin build --release --out dist --zig \  
            --target powerpc64le-unknown-linux-gnu \  
            --interpreter 3.10 3.11 3.12 3.13 3.13t 3.14 3.14t pypy3.11
